import { VariantExplorer } from "@/components/VariantExplorer";

export default function VariantsPage() {
  return (
    <div className="space-y-6">
      <header className="card-surface p-6 sm:p-8">
        <h1 className="text-3xl font-semibold text-white">VCF Variant Explorer</h1>
        <p className="mt-3 max-w-3xl text-slate-300">
          Browser-based VCF parser and explorer for filtered variant results generated by the Galaxy workflow.
        </p>
      </header>
      <VariantExplorer />
    </div>
  );
}
