import { DownloadCard } from "@/components/DownloadCard";
import { PageHeader } from "@/components/PageHeader";

const artifacts = [
  {
    title: "Galaxy Workflow File",
    description: "Reusable Galaxy workflow exported from the original project pipeline.",
    fileName: "galaxy-workflow.ga",
    href: "/galaxy-workflow.ga"
  },
  {
    title: "Project Report (PDF)",
    description: "Original project documentation describing analysis stages and interpretation.",
    fileName: "galaxy-project.pdf",
    href: "/galaxy-project.pdf"
  },
  {
    title: "Filtered VCF Result",
    description: "Variant call set filtered for downstream exploration and interpretation.",
    fileName: "filtered-variants.vcf",
    href: "/filtered-variants.vcf"
  },
  {
    title: "GitHub Repository",
    description: "Original source repository and project artifacts.",
    fileName: "LEO0331/Genomic-Data-Science-with-Galaxy-Project",
    href: "https://github.com/LEO0331/Genomic-Data-Science-with-Galaxy-Project"
  }
];

export default function DownloadsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reusable Outputs"
        title="Downloads & Artifacts"
        description="Access workflow and analysis artifacts generated by the Galaxy-based genomic variant-calling pipeline."
      />

      <section className="grid gap-4 md:grid-cols-2">
        {artifacts.map((artifact) => (
          <DownloadCard key={artifact.title} {...artifact} ctaLabel={artifact.href.startsWith("http") ? "Open" : "Download"} />
        ))}
      </section>
    </div>
  );
}
